server:
 port: 8085
 address: 192.168.39.118
 session-timeout: 30
spring:
 mvc:
   servlet:
     load-on-startup: 1
  # 数据源配置，请修改为你项目的实际配置
 datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver	
    url: jdbc:sqlserver://localhost:1433;DatabaseName=Prod
    username: sa
    password: 123456
    
 